# Generated by Django 3.1 on 2020-10-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201005_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_authors', 'Can create, update and delete authors'),)},
        ),
    ]
